### PR TITLE
Added resource: ScalaCourses.com / GetScala.com

### PR DESCRIPTION
**Pull request by mslinn**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
You should probably make a more descriptive commit message.

Also, it looks like you made a copy of `content.json` for some reason? That additional file should not be included.

**Comment by mslinn** [comment]
I updated my fork so the extra file is no longer there, and rewrote the git commit message so it is more descriptive. Is there anything else I need to do in order to update the pull request?

**Comment by Nightfirecat** [comment]
I hate to break it to you, but it's still in the same state as before; you may find it easier to revert to master, then reattempt your change. Maybe try the following:

```
git rm content.json~
git commit -am 'Remove erroneous file'
```

And if you're familiar with interactive rebasing, you could also clean up the commit history with the following:

```
git rebase -i 55a0272
```

The commit description is, however, much improved. :+1:

**Comment by mslinn** [comment]
Thanks for your patience. How is this?

**Comment by Nightfirecat** [comment]
That should be alright.

P.S. For full transparency, I should say that I don't actually have power to merge this PR &mdash; I'm just a random guy who likes contributing (and aiding in contributions) to open-source projects. Hopefully @JonHMChan checks on the active PRs for this repository soon to actually get things merged.

**Comment by JonHMChan** [comment]
@mslinn I've taken a look at the resource you've added here, and it looks like these are paid resources for learning Scala, without much instructional content available directly. This doesn't align with guideline #1 on the Contribution Guidelines: "Links should be free (no pay walls) and take the user immediately to the relevant information"

Going to close.

**Pull request closed without merging**
