### PR TITLE
Adding to D3 Box

### PR DESCRIPTION
**Pull request by JayK31**
Hey Jon,

This isn't so much a single tutorial as opposed to links to a bunch of useful D3 resources that explain the basic concepts of D3. I gave it a level 0, although there are some links that some might consider to be intermediate. The list is vast, so I'm not sure if it's appropriate for BB, but I used it extensively when I was learning D3 and found it really helpful. Cheers!

Jay

### CODE REVIEW

**Comment by JonHMChan** [comment]
I generally don't put in aggregations of tutorials because it's hard to accurately categorize difficulty and usually counters the purpose of presenting the user with a clear, recommended resource. If there are particular resources in there that you think are particularly good, I would split that out into its own link with the right difficulty.

**Comment by JayK31** [comment]
Hi Jon,

Yeah I figured that would be an issue. I'll split up the links I found most
useful and add them.

**Comment by JayK31** [comment]
Added a link from a different tutorial. Great beginner tutorial that feeds
into some lower-intermediate topics towards the end.

**Comment by JonHMChan** [comment]
Manually added in.

**Pull request closed without merging**
