### PR TITLE
Add some JavaScript content

### PR DESCRIPTION
**Pull request by vicmaster**
- Fight Code Game
- CodeWars
- Mozilla JavaScript Documentation

### CODE REVIEW

**Comment by vicmaster** [comment]
thoughts?

**Comment by JonHMChan** [comment]
I like the two links Codewards and Fight Code - but I actually think we can leave out the Mozilla documentation since it's the home link :)

**Comment by vicmaster** [comment]
Ok, I'll do the changes, thank you :)

**Comment by vicmaster** [comment]
Done :shipit:

**Pull request merged**
